version: '3.8'

services:
  mtg-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtg-mcp-server
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    # Standard I/O mode for MCP - no port binding needed for stdio transport
    # If you need TCP transport in the future, uncomment the ports section
    # ports:
    #   - "3000:3000"
    
    # Mount volume to persist any future cache/data
    volumes:
      - mtg_cache:/app/cache
    
    # Resource limits to maintain performance preservation as per guidelines
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "echo", "{\"jsonrpc\": \"2.0\", \"method\": \"initialize\", \"params\": {\"protocolVersion\": \"2024-11-05\", \"capabilities\": {}, \"clientInfo\": {\"name\": \"health-check\"}}, \"id\": 1}", "|", "./mtg-mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mtg_cache:
    driver: local
